//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_donation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonationEntities : DbContext
    {
        public DonationEntities()
            : base("name=DonationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_donationdetails> tbl_donationdetails { get; set; }
        public virtual DbSet<tbl_donationtype> tbl_donationtype { get; set; }
        public virtual DbSet<tbl_registeruserdetail> tbl_registeruserdetail { get; set; }
        public virtual DbSet<tbl_role> tbl_role { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
