//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_donation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_donationdetails
    {
        public int donationdetailid { get; set; }
        public Nullable<int> donationtypeid { get; set; }
        public Nullable<int> regid { get; set; }
        public Nullable<bool> recurgift { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual tbl_registeruserdetail tbl_registeruserdetail { get; set; }
        public virtual tbl_donationtype tbl_donationtype { get; set; }
    }
}
