//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_donation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_user
    {
        public int userid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public Nullable<int> roleid { get; set; }
        public Nullable<int> regid { get; set; }
    
        public virtual tbl_role tbl_role { get; set; }
        public virtual tbl_registeruserdetail tbl_registeruserdetail { get; set; }
    }
}
