//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_donation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_donationtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_donationtype()
        {
            this.tbl_donationdetails = new HashSet<tbl_donationdetails>();
        }
    
        public int donationtypeid { get; set; }
        public string donationname { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_donationdetails> tbl_donationdetails { get; set; }
    }
}
